---
- name: Install dependencies
  become: yes
  apt: pkg={{item}} state=installed
  with_items:
    - nodejs
    - npm

- name: npm local install
  become: yes
  npm: name={{item}} path=/tmp/bamboo-app
  with_items:
    - httpdispatcher

