---
- name: Install dependencies
  become: yes
  apt: pkg={{item}} state=installed
  with_items:
    - nodejs
    - npm

- name: npm global install
  become: yes
  npm: name={{item}} path=/home/osboxes/Public/bamboo-app
  with_items:
    - httpdispatcher

